import Lessons.SessionOne;
import Lessons.SessionTwo;
import io.reactivex.Observable;
import io.reactivex.Observer;
import io.reactivex.disposables.Disposable;
import io.reactivex.functions.Action;
import io.reactivex.functions.Consumer;
import io.reactivex.observables.ConnectableObservable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        //Sample hello world
        //System.out.println(new App().getGreeting());

        //SessionOne
        //SessionOne.SummerizingSessionOne();

        //SessionTwo
        SessionTwo two = new SessionTwo();
        //two.sampleForObserverObject();
        //two.sampleLambdaObserver();

        //Cold observable example
        //two.coldObservableExample();

        //Hot ObservableExample using connectableObservable.
        //two.hotObservableExample();

        //Onrange observable factory
        //two.rangeObservable();

        //Interval observable
        //two.intervalObservable();
        //two.trickyColdIntervalObservable();
        //two.trickyHotIntervalObservable();

        //Empty Observable
        two.emptyObservable();

    }


}
